// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu1n0AbkQ1BOGw19OXiCfGjtCTPHHf8JU',
    appId: '1:762727701986:web:c4f42a87239b43ea6bedbb',
    messagingSenderId: '762727701986',
    projectId: 'prefer-f2fad',
    authDomain: 'prefer-f2fad.firebaseapp.com',
    storageBucket: 'prefer-f2fad.appspot.com',
    measurementId: 'G-5433YENW9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWzkoVQl3ysax4v1BWMvMFpeN7pHi2BIs',
    appId: '1:762727701986:android:56f95ad7bcf777f16bedbb',
    messagingSenderId: '762727701986',
    projectId: 'prefer-f2fad',
    storageBucket: 'prefer-f2fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY_0N-eUMUJv7bsaP4E4qZjJTmBOt39Nw',
    appId: '1:762727701986:ios:e2cdb0d0c0daad7a6bedbb',
    messagingSenderId: '762727701986',
    projectId: 'prefer-f2fad',
    storageBucket: 'prefer-f2fad.appspot.com',
    iosClientId: '762727701986-qeoukj5sacee2k7700pg54dsm6d68l9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpMe',
  );
}
